SET DEFINE OFF;
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '본다빈치뮤지엄 능동', '999+', '전시관', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '서울어린이대공원동물원', '568', '동물원', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '건대맛의거리', '72', '먹자거리', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '서울어린이대공원구의문', '70', '부속건물', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '건대양꼬치골목', '51', '도보코스', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '건대로데오거리', '42', '도보코스', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '서울어린이대공원물놀이장', '37', '부속건물', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '서울어린이대공원동물공연장', '33', '부속건물', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '뚝섬한강공원인공암벽장', '29', '부속시설', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '능동로분수광장', '29', '근린공원', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '서울어린이대공원꿈틀꿈틀놀이터', '24', '부속건물', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '광진광장', '17', '근린공원', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '육영재단어린이회관과학관', '15', '전시관', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '서울어린이대공원동물원바다동물관', '12', '부속시설', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '건국대학교 박물관', '12', '박물관', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '느티나무공원', '11', '근린공원', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '서울어린이대공원전래동화마을', '10', '부속건물', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', 'SKT 5GX 라운지', '9', '관람,체험', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '서울어린이대공원동물원초식동물마을', '9', '부속시설', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '화양공원', '8', '근린공원', 'nan');
insert into PLACES (STATION_NAME, PLACE_NAME, REV_NUM, CTGR, URL) values ('Gundae', '건국대학교 모두의거리', '1', '거리,골목', 'nan');
