update restaurants set ctgrgroup = '양식' where ctgr = '프랑스음식';
update restaurants set ctgrgroup = '한식' where ctgr = '매운탕,해물탕';
update restaurants set ctgrgroup = '한식' where ctgr = '한식';
update restaurants set ctgrgroup = '일식' where ctgr = '일식당';
update restaurants set ctgrgroup = '한식' where ctgr = '국수';
update restaurants set ctgrgroup = '양식' where ctgr = '101번지남산돈까스';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '카페,디저트';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '베이커리';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '카페';
update restaurants set ctgrgroup = '주점' where ctgr = '곱창,막창,양';
update restaurants set ctgrgroup = '주점' where ctgr = '요리주점';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '양꼬치';
update restaurants set ctgrgroup = '주점' where ctgr = '닭발';
update restaurants set ctgrgroup = '한식' where ctgr = '소고기구이';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '도시락,컵밥';
update restaurants set ctgrgroup = '한식' where ctgr = '찌개,전골';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '피자';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '중식당';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '치킨,닭강정';
update restaurants set ctgrgroup = '일식' where ctgr = '샤브샤브';
update restaurants set ctgrgroup = '주점' where ctgr = '바(BAR)';
update restaurants set ctgrgroup = '양식' where ctgr = '돈가스';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '종합분식';
update restaurants set ctgrgroup = '주점' where ctgr = '맥주,호프';
update restaurants set ctgrgroup = '양식' where ctgr = '육류,고기요리';
update restaurants set ctgrgroup = '양식' where ctgr = '스파게티,파스타전문';
update restaurants set ctgrgroup = '한식' where ctgr = '곰탕,설렁탕';
update restaurants set ctgrgroup = '한식' where ctgr = '기사식당';
update restaurants set ctgrgroup = '한식' where ctgr = '족발,보쌈';
update restaurants set ctgrgroup = '한식' where ctgr = '국밥';
update restaurants set ctgrgroup = '일식' where ctgr = '이자카야';
update restaurants set ctgrgroup = '한식' where ctgr = '닭갈비';
update restaurants set ctgrgroup = '한식' where ctgr = '주꾸미요리';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '33떡볶이';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '떡볶이';
update restaurants set ctgrgroup = '주점' where ctgr = '포장마차';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '브런치';
update restaurants set ctgrgroup = '일식' where ctgr = '우동,소바';
update restaurants set ctgrgroup = '한식' where ctgr = '추어탕';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '베트남음식';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '차';
update restaurants set ctgrgroup = '양식' where ctgr = '양식';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '테이크아웃커피';
update restaurants set ctgrgroup = '한식' where ctgr = '해물,생선요리';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '햄버거';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '야식';
update restaurants set ctgrgroup = '양식' where ctgr = '이탈리아음식';
update restaurants set ctgrgroup = '한식' where ctgr = '칼국수,만두';
update restaurants set ctgrgroup = '주점' where ctgr = '단란주점';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '72420';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '74떡뽀끼';
update restaurants set ctgrgroup = '한식' where ctgr = '순대,순댓국';
update restaurants set ctgrgroup = '한식' where ctgr = '돼지고기구이';
update restaurants set ctgrgroup = '한식' where ctgr = '정육식당';
update restaurants set ctgrgroup = '한식' where ctgr = '한정식';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '홍차전문점';
update restaurants set ctgrgroup = '한식' where ctgr = '퓨전음식';
update restaurants set ctgrgroup = '양식' where ctgr = '스테이크,립';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '과일,주스전문점';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '케이크전문';
update restaurants set ctgrgroup = '주점' where ctgr = '술집';
update restaurants set ctgrgroup = '한식' where ctgr = '전,빈대떡';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '아시아음식';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '샌드위치';
update restaurants set ctgrgroup = '한식' where ctgr = 'JVL부대찌개';
update restaurants set ctgrgroup = '양식' where ctgr = '뷔페';
update restaurants set ctgrgroup = '한식' where ctgr = '두부요리';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '김밥';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '아이스크림';
update restaurants set ctgrgroup = '한식' where ctgr = '냉면';
update restaurants set ctgrgroup = '양식' where ctgr = '와인';
update restaurants set ctgrgroup = '한식' where ctgr = '백숙,삼계탕';
update restaurants set ctgrgroup = '일식' where ctgr = '생선회';
update restaurants set ctgrgroup = '일식' where ctgr = '장어,먹장어요리';
update restaurants set ctgrgroup = '양식' where ctgr = '푸드코트';
update restaurants set ctgrgroup = '양식' where ctgr = '패밀리레스토랑';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '태국음식';
update restaurants set ctgrgroup = '한식' where ctgr = '닭요리';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '인도음식';
update restaurants set ctgrgroup = '한식' where ctgr = '아귀찜,해물찜';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '라이브카페';
update restaurants set ctgrgroup = '일식' where ctgr = '초밥,롤';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '만두';
update restaurants set ctgrgroup = '주점' where ctgr = '유흥주점';
update restaurants set ctgrgroup = '한식' where ctgr = '가야밀면';
update restaurants set ctgrgroup = '한식' where ctgr = '오리요리';
update restaurants set ctgrgroup = '한식' where ctgr = '막국수';
update restaurants set ctgrgroup = '한식' where ctgr = '갈비탕';
update restaurants set ctgrgroup = '양식' where ctgr = '멕시코,남미음식';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '분식';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '갓식빵';
update restaurants set ctgrgroup = '주점' where ctgr = '강남맥주';
update restaurants set ctgrgroup = '한식' where ctgr = '조개요리';
update restaurants set ctgrgroup = '한식' where ctgr = '감자탕';
update restaurants set ctgrgroup = '한식' where ctgr = '보리밥';
update restaurants set ctgrgroup = '한식' where ctgr = '쌈밥';
update restaurants set ctgrgroup = '일식' where ctgr = '복어요리';
update restaurants set ctgrgroup = '한식' where ctgr = '강화통통생고기';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '다방';
update restaurants set ctgrgroup = '한식' where ctgr = '낙지요리';
update restaurants set ctgrgroup = '한식' where ctgr = '사철,영양탕';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '카레';
update restaurants set ctgrgroup = '한식' where ctgr = '한식뷔페';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '호떡';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '빙수';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '라면';
update restaurants set ctgrgroup = '일식' where ctgr = '일본식라면';
update restaurants set ctgrgroup = '한식' where ctgr = '닭볶음탕';
update restaurants set ctgrgroup = '한식' where ctgr = '비빔밥';
update restaurants set ctgrgroup = '한식' where ctgr = '고기원칙';
update restaurants set ctgrgroup = '한식' where ctgr = '고기뷔페';
update restaurants set ctgrgroup = '일식' where ctgr = '일식튀김,꼬치';
update restaurants set ctgrgroup = '일식' where ctgr = '고레카레';
update restaurants set ctgrgroup = '일식' where ctgr = '덮밥';
update restaurants set ctgrgroup = '한식' where ctgr = '찜닭';
update restaurants set ctgrgroup = '한식' where ctgr = '백반,가정식';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '오뎅,꼬치';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '북카페';
update restaurants set ctgrgroup = '주점' where ctgr = '전통,민속주점';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '양갈비';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '와플';
update restaurants set ctgrgroup = '일식' where ctgr = '생선구이';
update restaurants set ctgrgroup = '한식' where ctgr = '반찬가게';
update restaurants set ctgrgroup = '한식' where ctgr = '향토음식';
update restaurants set ctgrgroup = '일식' where ctgr = '오징어요리';
update restaurants set ctgrgroup = '일식' where ctgr = '굴요리';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '핫도그';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '다이어트,샐러드';
update restaurants set ctgrgroup = '한식' where ctgr = '음식점';
update restaurants set ctgrgroup = '한식' where ctgr = '대게요리';
update restaurants set ctgrgroup = '일식' where ctgr = '게요리';
update restaurants set ctgrgroup = '양식' where ctgr = '스페인음식';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '플라워카페';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '남도분식';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '토스트';
update restaurants set ctgrgroup = '한식' where ctgr = '이북음식';
update restaurants set ctgrgroup = '양식' where ctgr = '오므라이스';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '슬라임카페';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '크레페';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '달떡볶이';
update restaurants set ctgrgroup = '일식' where ctgr = '달빛오징어광어';
update restaurants set ctgrgroup = '일식' where ctgr = '달쫀';
update restaurants set ctgrgroup = '한식' where ctgr = '닭발먹은새우';
update restaurants set ctgrgroup = '한식' where ctgr = '떡카페';
update restaurants set ctgrgroup = '한식' where ctgr = '대게나라';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '대구근대골목단팥빵';
update restaurants set ctgrgroup = '주점' where ctgr = '대구형제막창';
update restaurants set ctgrgroup = '주점' where ctgr = '대반전';
update restaurants set ctgrgroup = '한식' where ctgr = '죽';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '도넛';
update restaurants set ctgrgroup = '양식' where ctgr = '채식,샐러드뷔페';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '딤섬,중식만두';
update restaurants set ctgrgroup = '한식' where ctgr = '해장국';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '커피가공,제조';
update restaurants set ctgrgroup = '일식' where ctgr = '전복요리';
update restaurants set ctgrgroup = '양식' where ctgr = '독일음식';
update restaurants set ctgrgroup = '한식' where ctgr = '사찰음식';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '만년닭강정';
update restaurants set ctgrgroup = '일식' where ctgr = '해산물뷔페';
update restaurants set ctgrgroup = '한식' where ctgr = '무한리필 마포서서갈비';
update restaurants set ctgrgroup = '한식' where ctgr = '무한장어';
update restaurants set ctgrgroup = '한식' where ctgr = '문래돼지불백';
update restaurants set ctgrgroup = '한식' where ctgr = '문배동육칼';
update restaurants set ctgrgroup = '주점' where ctgr = '뮌헨1589';
update restaurants set ctgrgroup = '주점' where ctgr = '미녀닭발';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '후렌치후라이';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '미스터빠삭';
update restaurants set ctgrgroup = '주점' where ctgr = '미인닭발';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '미친양꼬치';
update restaurants set ctgrgroup = '주점' where ctgr = '민혁이네외국포차';
update restaurants set ctgrgroup = '주점' where ctgr = '밀겨울';
update restaurants set ctgrgroup = '주점' where ctgr = '밀도';
update restaurants set ctgrgroup = '일식' where ctgr = '바닷가재요리';
update restaurants set ctgrgroup = '한식' where ctgr = '바람부리명태찜';
update restaurants set ctgrgroup = '일식' where ctgr = '바른스시';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '초콜릿전문점';
update restaurants set ctgrgroup = '양식' where ctgr = '프랜차이즈본사';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '베이글';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '불타는여고24시떡볶이';
update restaurants set ctgrgroup = '주점' where ctgr = '블루보틀';
update restaurants set ctgrgroup = '주점' where ctgr = '슈';
update restaurants set ctgrgroup = '일식' where ctgr = '킹크랩요리';
update restaurants set ctgrgroup = '한식' where ctgr = '삼청동국수';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '한방카페';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = 'nan';
update restaurants set ctgrgroup = '일식' where ctgr = '일식,초밥뷔페';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '스마일명품찹쌀꽈배기';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '스마일찹쌀꽈배기';
update restaurants set ctgrgroup = '양식' where ctgr = '스파게티스토리';
update restaurants set ctgrgroup = '한식' where ctgr = '시골한우시골돼지';
update restaurants set ctgrgroup = '한식' where ctgr = '시래옥';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '신떡순신천할매떡볶이';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '신룽푸마라탕';
update restaurants set ctgrgroup = '한식' where ctgr = '신사골옛날감자탕';
update restaurants set ctgrgroup = '한식' where ctgr = '신의주부대찌개';
update restaurants set ctgrgroup = '주점' where ctgr = '불닭';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '씨앗호떡부산떡볶이';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '호두과자';
update restaurants set ctgrgroup = '한식' where ctgr = '아부찌부대찌개';
update restaurants set ctgrgroup = '주점' where ctgr = '안경할머니곱창';
update restaurants set ctgrgroup = '한식' where ctgr = '애솔촌돼지';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '얌얌식빵';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '커피번';
update restaurants set ctgrgroup = '일식' where ctgr = '오니기리';
update restaurants set ctgrgroup = '한식' where ctgr = '주먹밥';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '문화,유적';
update restaurants set ctgrgroup = '중식, 동양식' where ctgr = '터키음식';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '이흥용과자점';
update restaurants set ctgrgroup = '주점' where ctgr = '인근주민';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '인정국물떡볶이';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '일공공키친';
update restaurants set ctgrgroup = '한식' where ctgr = '일도씨닭갈비';
update restaurants set ctgrgroup = '한식' where ctgr = '일석삼조버섯매운탕';
update restaurants set ctgrgroup = '일식' where ctgr = '일품정';
update restaurants set ctgrgroup = '일식' where ctgr = '일품향';
update restaurants set ctgrgroup = '일식' where ctgr = '잇또라멘';
update restaurants set ctgrgroup = '분식, 패스트푸드' where ctgr = '장수통닭';
update restaurants set ctgrgroup = '한식' where ctgr = '장수한우곱창';
update restaurants set ctgrgroup = '한식' where ctgr = '24시전주콩나물국밥';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '애견카페';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '갤러리카페';
update restaurants set ctgrgroup = '카페, 디저트' where ctgr = '스터디카페';
update restaurants set ctgrgroup = '주점' where ctgr = '푸드트럭';
update restaurants set ctgrgroup = '주점' where ctgr = '포차세끼';
update restaurants set ctgrgroup = '주점' where ctgr = '공방';
update restaurants set ctgrgroup = '한식' where ctgr = '화덕고깃간';
