import os
import csv
dir_csv = (os.path.dirname(os.getcwd()) + "\\Station\\Stations.csv").replace("\\", "/")

csv_file = open(dir_csv, "w+t", newline = '')

line_1 = ['Soyosan Station', 'Dongducheon Station', 'Bosan Station', 'Dongducheon Central Station', 'Jihaeng Station', 'Deokjeong Station', 'Deokgye Station', 'Yangju Station', 'Nokyang Station', 'possible station', 'Uijeongbu Station', 'Hoeryong Station', 'Mangwolsa Station', 'Dobongsan Station', 'Dobong Station', 'Banghak Station', 'Changdong Station', 'Nokcheon Station', 'Wolgye Station', 'Kwangwoon University Station', 'Seokgye Station', 'Sinimun Station', 'Hankuk University of Foreign Studies station', 'Hoegi Station', 'Cheongnyangni Station', 'Jegi-dong Station', 'Sinseol-dong Station', 'Dongmyo Station', 'Dongdaemun Station', 'Jongno 5-ga Station', 'Jongno 3-ga Station', 'Jonggak Station', 'City Hall Station', 'Seoul Station', 'Namyeong Station', 'Yongsan Station', 'Noryangjin Station', 'Daebang Station', 'Singil Station', 'Yeongdeungpo Station', 'Sindorim Station', 'Guro Station', 'Guil Station', 'opening station', 'Oryu-dong Station', 'Onsu Station', 'Yeokgok Station', 'Sosa Station', 'Bucheon Station', 'Jungdong Station', 'Songnae Station', 'Bugae Station', 'Bupyeong Station', 'Baegun Station', 'Dongam Station', 'Ganseok Station', 'Juan Station', 'Dohwa Station', 'Jemulpo Station', 'Dowon Station', 'East Incheon Station', 'Incheon Station', 'Gasan Digital Complex Area', 'Doksan Station', 'Geumcheon-gu Office Station', 'Gwangmyeong Station', 'Seoksu Station', 'Gwanak Station', 'Anyang Station', 'Myeonghak Station', 'Geumjeong Station', 'Gunpo Station', 'Dangjeong Station', 'Uiwang Station', 'Sungkyunkwan University Station', 'Hwaseo Station', 'Suwon Station', 'Seryu Station', 'Byeongjeom Station', 'Seodongtan Station', 'Sema Station', 'Osan University Station', 'Osan Station', 'Jinwi Station', 'Songtan Station', 'Seojeongri Station', 'Jije Station', 'Pyeongtaek Station', 'Seonghwan Station', 'Jiksan Station', 'Dujeong Station', 'Cheonan Station', 'Bongmyeong Station', 'Ssangyong Station', 'Asan Station', 'Baebang Station', 'Onyang Hot Spring Station', 'Sinchang Station']
line_2 = ['City Hall Station', 'Euljiro Station', 'Euljiro 3-ga Station', 'Euljiro 4-ga Station', 'Dongdaemun History and Culture Park Station', 'Sindang Station', 'Sangwangsimni Station', 'Wangsimni Station', 'Hanyang University Station', 'Ttukseom Station', 'Seongsu Station', 'Yongdap Station', 'Sindap Station', 'Yongdu Station', 'Sinseol-dong Station', 'Konkuk University Station', 'Guui Station', 'Gangbyeon Station', 'Jamsilnaru Station', 'Jamsil Station', 'Jamsil Saenae Station', 'Sports Complex Station', 'Samseong Station', 'Seonreung Station', 'Yeoksam Station', 'Gangnam Station', 'abutment station', 'Seocho Station', 'Bangbae Station', 'Sadang Station', 'Nakseongdae Station', 'Seoul National University Station', 'Bongcheon Station', 'Sillim Station', 'Sindaebang Station', 'Guro Digital Complex Area', 'Daelim Station', 'Sindorim Station', 'Dorimcheon Station', 'Yangcheon-gu Office Station', 'Sinjeongnegeori Station', 'Kkachisan Station', 'Munrae Station', 'Yeongdeungpo-gu Office Station', 'Dangsan Station', 'Hapjeong Station', 'Hongdae Station', 'Sinchon Station', 'Ewha Womans University Station', 'Ahyeon Station', 'Chungjeongno Station']
line_3 = ['Wonheung Station', 'Daehwa Station', 'Juyeop Station', 'Jeongbalsan Station', 'Madu Station', 'Baekseok Station', 'Daegok Station', 'Hwajeong Station', 'Wondang Station', 'Samsong Station', 'Jichuk Station', 'Gupabal Station', 'Yeonsinnae Station', 'Bulgwang Station', 'Nokbeon Station', 'Hongje Station', 'Muakjae Station', 'Independence Literature Translation', 'Gyeongbokgung Station', 'Anguk Station', 'Jongno 3-ga Station', 'Euljiro 3-ga Station', 'Chungmuro Station', 'Dongdaegu Station', 'Yaksu Station', 'Kumho Station', 'Oksu Station', 'Apgujeong Station', 'Sinsa Station', 'Jamwon Station', 'Express Bus Terminal Station', 'abutment station', 'Nambu Terminal Station', 'Yangjae Station', 'Maebong Station', 'Dogok Station', 'Daechi Station', 'Hakyeoul Station', 'Daecheong Station', 'Ilwon Station', 'Suseo Station', 'Garak Market Station', 'Police Hospital Station', 'Ogeum Station']
line_4 = ['Dangogae Station', 'Sanggye Station', 'Nowon Station', 'Changdong Station', 'Ssangmun Station', 'Suyu Station', 'Mia Station', 'Mia Intersection Station', 'Gileum Station', "Sungshin Women's University Station", 'Hansung University Station', 'Hyehwa Station', 'Dongdaemun Station', 'Dongdaemun History and Culture Park Station', 'Chungmuro Station', 'Myeong-dong Station', 'Hoehyeon Station', 'Seoul Station', 'Sookmyung University Station', 'Triangle area', 'Shinyongsan Station', 'Ichon Station', 'Dongjak Station', 'Isu Station', 'Sadang Station', 'Namtaryeong Station', 'Sunbawi Station', 'Gyeongma Park Station', 'Grand Park Station', 'Gwacheon Station', 'Gwacheon Government Complex Station', 'Indeokwon Station', 'Pyeongchon Station', 'Beomgye Station', 'Geumjeong Station', 'Sanbon Station', 'Surisan Station', 'Daeyami Station', 'Banwol Station', 'Sangnoksu Station', 'Hankuk University Station', 'Central Station', 'Gojan Station', 'super-region', 'Ansan Station', 'Singil Oncheon Station', 'Jeongwang Station', 'Oido Station']
line_5 = ['Banghwa Station', 'Gaehwasan Station', 'Gimpo Airport Station', 'Songjeong Station', 'Magok Station', 'Balsan Station', 'Ujangsan Station', 'Hwagok Station', 'Kkachisan Station', 'Sinjeong Station', 'Mokdong Station', 'Omok Bridge Station', 'Yangpyeong Station', 'Yeongdeungpo-gu Office Station', 'Yeongdeungpo Market Station', 'Singil Station', 'Yeouido Station', 'Y 여의inaru Station', 'Mapo Station', 'Gongdeok Station', 'Aeogae Station', 'Chungjeongno Station', 'Seodaemun Station', 'Gwanghwamun Station', 'Jongno 3-ga Station', 'Euljiro 4-ga Station', 'Dongdaemun History and Culture Park Station', 'Cheonggu Station', 'Singeumho Station', 'Haengdang Station', 'Wangsimni Station', 'Majang Station', 'Dapsimni Station', 'Janghanpyeong Station', 'Gunja Station', 'Achasan Station', 'Gwangnaru Station', 'Cheonho Station', 'Gangdong Station', 'Gildong Station', 'Bendari Station', 'Myeongil Station', 'Godeok Station', 'Sangil-dong Station', 'Dunchon-dong Station', 'Olympic Park Station', 'Bangi Station', 'Ogeum Station', 'Gaerong Station', 'Geoyeo Station', 'Macheon Station']
line_6 = ['Eungam Station', 'Yeokchon Station', 'Bulgwang Station', 'Dokbawi Station', 'Yeonsinnae Station', 'Gusan Station', 'Saejeol Station', 'Jeungsan Station', 'Digital Media City Station', 'World Cup Stadium Station', 'Mapo-gu Office Station', 'Mangwon Station', 'Hapjeong Station', 'Sangsu Station', 'Gwangheungchang Station', 'Daeheung Station', 'Gongdeok Station', 'Hyochang Park Station', 'Triangle area', 'Noksapyeong Station', 'Itaewon Station', 'Hangangjin Station', 'Bertigogae Station', 'Yaksu Station', 'Cheonggu Station', 'Sindang Station', 'Dongmyo Station', 'Changshin Station', 'Bomun Station', 'Anam Station', 'Korea University Station', 'Wolgok Station', 'Sangwolgok Station', 'Dolgotji Station', 'Seokgye Station', 'Taereung Station', 'Hwarangdae Station', 'Bonghwasan Station']
line_7 = ['Jangam Station', 'Dobongsan Station', 'Suraksan Station', 'Madele Station', 'Nowon Station', 'relay station', 'Summer Station', 'Gongneung Station', 'Taereung Station', 'Mukgol Station', 'Junghwa Station', 'Sangbong Station', 'Myeonmok Station', 'Sagam Station', 'Yongmasan Station', 'Junggok Station', 'Gunja Station', "Children's Grand Park Station", 'Konkuk University Station', 'Ttuk Textile Garden Area', 'Cheongdam Station', 'Gangnam-gu Office Station', 'Hakdong Station', 'Nonhyeon Station', 'Banpo Station', 'Express Bus Terminal Station', 'Naebang Station', 'Isu Station', 'Namseong Station', 'Soongsil University Station', 'Sangdo Station', 'Jangseungbaegi Station', 'Sindaebang Samgeori Station', 'Boramae Station', 'Sinpung Station', 'Daelim Station', 'Namguro Station', 'Gasan Digital Complex Area', 'Cheolsan Station', 'Gwangmyeong Intersection Station', 'Cheonwang Station', 'Onsu Station', 'Kkachiul Station', 'Bucheon Stadium Station', 'Chunui Station', 'Sinjung-dong Station', 'Bucheon City Hall Station', 'Sangdong Station', 'Samsan Gymnasium Station', 'Gulpocheon Station', 'Bupyeong-gu Office Station']
line_8 = ['Amsa Station', 'Cheonho Station', 'Gangdong-gu Office Station', 'Mongchontoseong Station', 'Jamsil Station', 'Seokchon Station', 'Songpa Station', 'Garak Market Station', 'Munjeong Station', 'Zhang Ziyi', 'Bokjeong Station', 'Sanseong Station', 'Namhansanseong Station', 'Dandae Ogeori Station', 'Shinheung Station', 'Sujin Station', 'Moran Station']
line_9 = ['Gaehwa Station', 'Gimpo Airport Station', 'Airport Market Station', 'Sinbanghwa Station', 'Magoknaru Station', 'Yangcheonhyanggyo Station', 'Gayang Station', 'Jeungmi Station', 'Deungchon Station', 'Yeomchang Station', 'Sinmok-dong Station', 'Seonyudo Station', 'Dangsan Station', 'National Assembly Building Station', 'Yeouido Station', 'Saetgang Station', 'Noryangjin Station', 'Nodeul Station', 'Heukseok Station', 'Dongjak Station', 'Gubanpo Station', 'Sinbanpo Station', 'Express Bus Terminal Station', 'Sapyeong Station', 'Sinnonhyeon Station', 'Eonju Station', 'Seonjeongneung Station', 'Samseong Central Station', 'Bongeunsa Station', 'Sports Complex Station', 'Samjeon Station', 'Seokchon Ancient Tombs Station', 'Seokchon Station', 'Songpa Naru Station', 'Hansung Baekje Station', 'Olympic Park Station', 'Dunchon Oryun Station', 'Central Veterans Hospital Station']
data = [line_1, line_2, line_3, line_4, line_5, line_6, line_7, line_8, line_9]

wr = csv.writer(csv_file)

for line in data:
    i = 1
    for station in line:
        station = station.replace("\'", "\\\'")
        station = station.replace(" station", "")
        station = station.replace(" Station", "")
        wr.writerow([station, i])
    i += 1
csv_file.close()

