create table PLACES (STATION_NAME varchar(60), PLACE_NAME varchar(60), REV_NUM varchar(60), CTGR varchar(60), URL varchar(400));
ALTER TABLE PLACES ADD CONSTRAINT PLACE_NAME_PK PRIMARY KEY (PLACE_NAME, STATION_NAME);
ALTER TABLE PLACES MODIFY PLACE_NAME varchar (60) NOT NULL;
ALTER TABLE PLACES ADD CONSTRAINT PLACES_FK FOREIGN KEY (STATION_NAME) REFERENCES STATIONS (STATION_NAME);
