SET DEFINE OFF;
DROP TABLE mysql.PLACES;
CREATE TABLE mysql.PLACES (STATION_NAME VARCHAR(60), PLACE_NAME VARCHAR(60), REV_NUM VARCHAR(60), CTGR VARCHAR(60), URL VARCHAR(400));
CREATE UNIQUE INDEX PLACE_NAME_PK ON mysql.PLACES (PLACE_NAME);
ALTER TABLE mysql.PLACES ADD CONSTRAINT PLACE_NAME_PK PRIMARY KEY (PLACE_NAME);
ALTER TABLE mysql.PLACES MODIFY PLACE_NAME VARCHAR(60) NOT NULL;
ALTER TABLE mysql.PLACES ADD CONSTRAINT PLACES_FK FOREIGN KEY (STATION_NAME) REFERENCES mysql.STATIONS (STATION_NAME);
