SET DEFINE OFF;
DROP TABLE mysql.STATIONS;
create table mysql.STATIONS (STATION_NAME varchar(60), RATE FLOAT(1));
CREATE UNIQUE INDEX STATION_NAME_PK ON mysql.STATIONS (STATION_NAME);
ALTER TABLE mysql.STATIONS ADD CONSTRAINT STATION_NAME_PK PRIMARY KEY (STATION_NAME);
