SET DEFINE OFF;
DROP TABLE mysql.RESTAURANTS;
create table mysql.RESTAURANTS (STATION_NAME varchar(60), RESTAURANT_NAME varchar(60), REV_NUM varchar(60), CTGR varchar(60), URL varchar(400));
CREATE UNIQUE INDEX RESTAURANT_NAME_PK ON mysql.RESTAURANTS (RESTAURANT_NAME);
ALTER TABLE mysql.RESTAURANTS ADD CONSTRAINT RESTAURANT_NAME_PK PRIMARY KEY (RESTAURANT_NAME);
ALTER TABLE mysql.RESTAURANTS MODIFY COLUMN RESTAURANT_NAME VARCHAR(60) NOT NULL;
ALTER TABLE mysql.RESTAURANTS ADD CONSTRAINT RESTAURANT_FK FOREIGN KEY (STATION_NAME) REFERENCES mysql.STATIONS (STATION_NAME);
