SET DEFINE OFF;
DROP TABLE PLACES;
create table PLACES ("STATION_NAME" varchar(60), "PLACE_NAME" varchar(60), "REV_NUM" varchar(60), "CTGR" varchar(60), "URL" varchar(400));
CREATE UNIQUE INDEX "PLACE_NAME_PK" ON "PLACES" ("PLACE_NAME");
ALTER TABLE "PLACES" ADD CONSTRAINT "PLACE_NAME_PK" PRIMARY KEY ("PLACE_NAME");
ALTER TABLE "PLACES" MODIFY ("PLACE_NAME" NOT NULL ENABLE);
ALTER TABLE "PLACES" ADD CONSTRAINT "STATION_NAME_FK" FOREIGN KEY ("STATION_NAME") REFERENCES "STATIONS" ("STATION_NAME") ENABLE;
