SET DEFINE OFF;
DROP TABLE mysql.ACTIVITIES;
create table mysql.ACTIVITIES (STATION_NAME varchar(60), ACTIVITY_NAME varchar(60), REV_NUM varchar(60), CTGR varchar(60), URL varchar(400));
CREATE UNIQUE INDEX ACTIVITY_NAME_PK ON mysql.ACTIVITIES (ACTIVITY_NAME);
ALTER TABLE mysql.ACTIVITIES ADD CONSTRAINT ACTIVITY_NAME_PK PRIMARY KEY (ACTIVITY_NAME);
ALTER TABLE mysql.ACTIVITIES MODIFY ACTIVITY_NAME varchar(60) NOT NULL;
ALTER TABLE mysql.ACTIVITIES ADD CONSTRAINT ACTIVITIES_FK FOREIGN KEY (STATION_NAME) REFERENCES mysql.STATIONS (STATION_NAME);
