insert ignore into STATIONS (STATION_NAME) values ('Soyosan');
insert ignore into STATIONS (STATION_NAME) values ('Dongducheon');
insert ignore into STATIONS (STATION_NAME) values ('Bosan');
insert ignore into STATIONS (STATION_NAME) values ('Dongducheon Central');
insert ignore into STATIONS (STATION_NAME) values ('Jihaeng');
insert ignore into STATIONS (STATION_NAME) values ('Deokjeong');
insert ignore into STATIONS (STATION_NAME) values ('Deokgye');
insert ignore into STATIONS (STATION_NAME) values ('Yangju');
insert ignore into STATIONS (STATION_NAME) values ('Nokyang');
insert ignore into STATIONS (STATION_NAME) values ('possible');
insert ignore into STATIONS (STATION_NAME) values ('Uijeongbu');
insert ignore into STATIONS (STATION_NAME) values ('Hoeryong');
insert ignore into STATIONS (STATION_NAME) values ('Mangwolsa');
insert ignore into STATIONS (STATION_NAME) values ('Dobongsan');
insert ignore into STATIONS (STATION_NAME) values ('Dobong');
insert ignore into STATIONS (STATION_NAME) values ('Banghak');
insert ignore into STATIONS (STATION_NAME) values ('Changdong');
insert ignore into STATIONS (STATION_NAME) values ('Nokcheon');
insert ignore into STATIONS (STATION_NAME) values ('Wolgye');
insert ignore into STATIONS (STATION_NAME) values ('Kwangwoon University');
insert ignore into STATIONS (STATION_NAME) values ('Seokgye');
insert ignore into STATIONS (STATION_NAME) values ('Sinimun');
insert ignore into STATIONS (STATION_NAME) values ('Hankuk University of Foreign Studies');
insert ignore into STATIONS (STATION_NAME) values ('Hoegi');
insert ignore into STATIONS (STATION_NAME) values ('Cheongnyangni');
insert ignore into STATIONS (STATION_NAME) values ('Jegi-dong');
insert ignore into STATIONS (STATION_NAME) values ('Sinseol-dong');
insert ignore into STATIONS (STATION_NAME) values ('Dongmyo');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun');
insert ignore into STATIONS (STATION_NAME) values ('Jongno 5-ga');
insert ignore into STATIONS (STATION_NAME) values ('Jongno 3-ga');
insert ignore into STATIONS (STATION_NAME) values ('Jonggak');
insert ignore into STATIONS (STATION_NAME) values ('City Hall');
insert ignore into STATIONS (STATION_NAME) values ('Seoul');
insert ignore into STATIONS (STATION_NAME) values ('Namyeong');
insert ignore into STATIONS (STATION_NAME) values ('Yongsan');
insert ignore into STATIONS (STATION_NAME) values ('Noryangjin');
insert ignore into STATIONS (STATION_NAME) values ('Daebang');
insert ignore into STATIONS (STATION_NAME) values ('Singil');
insert ignore into STATIONS (STATION_NAME) values ('Yeongdeungpo');
insert ignore into STATIONS (STATION_NAME) values ('Sindorim');
insert ignore into STATIONS (STATION_NAME) values ('Guro');
insert ignore into STATIONS (STATION_NAME) values ('Guil');
insert ignore into STATIONS (STATION_NAME) values ('opening');
insert ignore into STATIONS (STATION_NAME) values ('Oryu-dong');
insert ignore into STATIONS (STATION_NAME) values ('Onsu');
insert ignore into STATIONS (STATION_NAME) values ('Yeokgok');
insert ignore into STATIONS (STATION_NAME) values ('Sosa');
insert ignore into STATIONS (STATION_NAME) values ('Bucheon');
insert ignore into STATIONS (STATION_NAME) values ('Jungdong');
insert ignore into STATIONS (STATION_NAME) values ('Songnae');
insert ignore into STATIONS (STATION_NAME) values ('Bugae');
insert ignore into STATIONS (STATION_NAME) values ('Bupyeong');
insert ignore into STATIONS (STATION_NAME) values ('Baegun');
insert ignore into STATIONS (STATION_NAME) values ('Dongam');
insert ignore into STATIONS (STATION_NAME) values ('Ganseok');
insert ignore into STATIONS (STATION_NAME) values ('Juan');
insert ignore into STATIONS (STATION_NAME) values ('Dohwa');
insert ignore into STATIONS (STATION_NAME) values ('Jemulpo');
insert ignore into STATIONS (STATION_NAME) values ('Dowon');
insert ignore into STATIONS (STATION_NAME) values ('East Incheon');
insert ignore into STATIONS (STATION_NAME) values ('Incheon');
insert ignore into STATIONS (STATION_NAME) values ('Gasan Digital Complex Area');
insert ignore into STATIONS (STATION_NAME) values ('Doksan');
insert ignore into STATIONS (STATION_NAME) values ('Geumcheon-gu Office');
insert ignore into STATIONS (STATION_NAME) values ('Gwangmyeong');
insert ignore into STATIONS (STATION_NAME) values ('Seoksu');
insert ignore into STATIONS (STATION_NAME) values ('Gwanak');
insert ignore into STATIONS (STATION_NAME) values ('Anyang');
insert ignore into STATIONS (STATION_NAME) values ('Myeonghak');
insert ignore into STATIONS (STATION_NAME) values ('Geumjeong');
insert ignore into STATIONS (STATION_NAME) values ('Gunpo');
insert ignore into STATIONS (STATION_NAME) values ('Dangjeong');
insert ignore into STATIONS (STATION_NAME) values ('Uiwang');
insert ignore into STATIONS (STATION_NAME) values ('Sungkyunkwan University');
insert ignore into STATIONS (STATION_NAME) values ('Hwaseo');
insert ignore into STATIONS (STATION_NAME) values ('Suwon');
insert ignore into STATIONS (STATION_NAME) values ('Seryu');
insert ignore into STATIONS (STATION_NAME) values ('Byeongjeom');
insert ignore into STATIONS (STATION_NAME) values ('Seodongtan');
insert ignore into STATIONS (STATION_NAME) values ('Sema');
insert ignore into STATIONS (STATION_NAME) values ('Osan University');
insert ignore into STATIONS (STATION_NAME) values ('Osan');
insert ignore into STATIONS (STATION_NAME) values ('Jinwi');
insert ignore into STATIONS (STATION_NAME) values ('Songtan');
insert ignore into STATIONS (STATION_NAME) values ('Seojeongri');
insert ignore into STATIONS (STATION_NAME) values ('Jije');
insert ignore into STATIONS (STATION_NAME) values ('Pyeongtaek');
insert ignore into STATIONS (STATION_NAME) values ('Seonghwan');
insert ignore into STATIONS (STATION_NAME) values ('Jiksan');
insert ignore into STATIONS (STATION_NAME) values ('Dujeong');
insert ignore into STATIONS (STATION_NAME) values ('Cheonan');
insert ignore into STATIONS (STATION_NAME) values ('Bongmyeong');
insert ignore into STATIONS (STATION_NAME) values ('Ssangyong');
insert ignore into STATIONS (STATION_NAME) values ('Asan');
insert ignore into STATIONS (STATION_NAME) values ('Baebang');
insert ignore into STATIONS (STATION_NAME) values ('Onyang Hot Spring');
insert ignore into STATIONS (STATION_NAME) values ('Sinchang');
insert ignore into STATIONS (STATION_NAME) values ('City Hall');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro 3-ga');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro 4-ga');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun History and Culture Park');
insert ignore into STATIONS (STATION_NAME) values ('Sindang');
insert ignore into STATIONS (STATION_NAME) values ('Sangwangsimni');
insert ignore into STATIONS (STATION_NAME) values ('Wangsimni');
insert ignore into STATIONS (STATION_NAME) values ('Hanyang University');
insert ignore into STATIONS (STATION_NAME) values ('Ttukseom');
insert ignore into STATIONS (STATION_NAME) values ('Seongsu');
insert ignore into STATIONS (STATION_NAME) values ('Yongdap');
insert ignore into STATIONS (STATION_NAME) values ('Sindap');
insert ignore into STATIONS (STATION_NAME) values ('Yongdu');
insert ignore into STATIONS (STATION_NAME) values ('Sinseol-dong');
insert ignore into STATIONS (STATION_NAME) values ('Konkuk University');
insert ignore into STATIONS (STATION_NAME) values ('Guui');
insert ignore into STATIONS (STATION_NAME) values ('Gangbyeon');
insert ignore into STATIONS (STATION_NAME) values ('Jamsilnaru');
insert ignore into STATIONS (STATION_NAME) values ('Jamsil');
insert ignore into STATIONS (STATION_NAME) values ('Jamsil Saenae');
insert ignore into STATIONS (STATION_NAME) values ('Sports Complex');
insert ignore into STATIONS (STATION_NAME) values ('Samseong');
insert ignore into STATIONS (STATION_NAME) values ('Seonreung');
insert ignore into STATIONS (STATION_NAME) values ('Yeoksam');
insert ignore into STATIONS (STATION_NAME) values ('Gangnam');
insert ignore into STATIONS (STATION_NAME) values ('abutment');
insert ignore into STATIONS (STATION_NAME) values ('Seocho');
insert ignore into STATIONS (STATION_NAME) values ('Bangbae');
insert ignore into STATIONS (STATION_NAME) values ('Sadang');
insert ignore into STATIONS (STATION_NAME) values ('Nakseongdae');
insert ignore into STATIONS (STATION_NAME) values ('Seoul National University');
insert ignore into STATIONS (STATION_NAME) values ('Bongcheon');
insert ignore into STATIONS (STATION_NAME) values ('Sillim');
insert ignore into STATIONS (STATION_NAME) values ('Sindaebang');
insert ignore into STATIONS (STATION_NAME) values ('Guro Digital Complex Area');
insert ignore into STATIONS (STATION_NAME) values ('Daelim');
insert ignore into STATIONS (STATION_NAME) values ('Sindorim');
insert ignore into STATIONS (STATION_NAME) values ('Dorimcheon');
insert ignore into STATIONS (STATION_NAME) values ('Yangcheon-gu Office');
insert ignore into STATIONS (STATION_NAME) values ('Sinjeongnegeori');
insert ignore into STATIONS (STATION_NAME) values ('Kkachisan');
insert ignore into STATIONS (STATION_NAME) values ('Munrae');
insert ignore into STATIONS (STATION_NAME) values ('Yeongdeungpo-gu Office');
insert ignore into STATIONS (STATION_NAME) values ('Dangsan');
insert ignore into STATIONS (STATION_NAME) values ('Hapjeong');
insert ignore into STATIONS (STATION_NAME) values ('Hongdae');
insert ignore into STATIONS (STATION_NAME) values ('Sinchon');
insert ignore into STATIONS (STATION_NAME) values ('Ewha Womans University');
insert ignore into STATIONS (STATION_NAME) values ('Ahyeon');
insert ignore into STATIONS (STATION_NAME) values ('Chungjeongno');
insert ignore into STATIONS (STATION_NAME) values ('Wonheung');
insert ignore into STATIONS (STATION_NAME) values ('Daehwa');
insert ignore into STATIONS (STATION_NAME) values ('Juyeop');
insert ignore into STATIONS (STATION_NAME) values ('Jeongbalsan');
insert ignore into STATIONS (STATION_NAME) values ('Madu');
insert ignore into STATIONS (STATION_NAME) values ('Baekseok');
insert ignore into STATIONS (STATION_NAME) values ('Daegok');
insert ignore into STATIONS (STATION_NAME) values ('Hwajeong');
insert ignore into STATIONS (STATION_NAME) values ('Wondang');
insert ignore into STATIONS (STATION_NAME) values ('Samsong');
insert ignore into STATIONS (STATION_NAME) values ('Jichuk');
insert ignore into STATIONS (STATION_NAME) values ('Gupabal');
insert ignore into STATIONS (STATION_NAME) values ('Yeonsinnae');
insert ignore into STATIONS (STATION_NAME) values ('Bulgwang');
insert ignore into STATIONS (STATION_NAME) values ('Nokbeon');
insert ignore into STATIONS (STATION_NAME) values ('Hongje');
insert ignore into STATIONS (STATION_NAME) values ('Muakjae');
insert ignore into STATIONS (STATION_NAME) values ('Independence Literature Translation');
insert ignore into STATIONS (STATION_NAME) values ('Gyeongbokgung');
insert ignore into STATIONS (STATION_NAME) values ('Anguk');
insert ignore into STATIONS (STATION_NAME) values ('Jongno 3-ga');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro 3-ga');
insert ignore into STATIONS (STATION_NAME) values ('Chungmuro');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaegu');
insert ignore into STATIONS (STATION_NAME) values ('Yaksu');
insert ignore into STATIONS (STATION_NAME) values ('Kumho');
insert ignore into STATIONS (STATION_NAME) values ('Oksu');
insert ignore into STATIONS (STATION_NAME) values ('Apgujeong');
insert ignore into STATIONS (STATION_NAME) values ('Sinsa');
insert ignore into STATIONS (STATION_NAME) values ('Jamwon');
insert ignore into STATIONS (STATION_NAME) values ('Express Bus Terminal');
insert ignore into STATIONS (STATION_NAME) values ('abutment');
insert ignore into STATIONS (STATION_NAME) values ('Nambu Terminal');
insert ignore into STATIONS (STATION_NAME) values ('Yangjae');
insert ignore into STATIONS (STATION_NAME) values ('Maebong');
insert ignore into STATIONS (STATION_NAME) values ('Dogok');
insert ignore into STATIONS (STATION_NAME) values ('Daechi');
insert ignore into STATIONS (STATION_NAME) values ('Hakyeoul');
insert ignore into STATIONS (STATION_NAME) values ('Daecheong');
insert ignore into STATIONS (STATION_NAME) values ('Ilwon');
insert ignore into STATIONS (STATION_NAME) values ('Suseo');
insert ignore into STATIONS (STATION_NAME) values ('Garak Market');
insert ignore into STATIONS (STATION_NAME) values ('Police Hospital');
insert ignore into STATIONS (STATION_NAME) values ('Ogeum');
insert ignore into STATIONS (STATION_NAME) values ('Dangogae');
insert ignore into STATIONS (STATION_NAME) values ('Sanggye');
insert ignore into STATIONS (STATION_NAME) values ('Nowon');
insert ignore into STATIONS (STATION_NAME) values ('Changdong');
insert ignore into STATIONS (STATION_NAME) values ('Ssangmun');
insert ignore into STATIONS (STATION_NAME) values ('Suyu');
insert ignore into STATIONS (STATION_NAME) values ('Mia');
insert ignore into STATIONS (STATION_NAME) values ('Mia Intersection');
insert ignore into STATIONS (STATION_NAME) values ('Gileum');
insert ignore into STATIONS (STATION_NAME) values ('Sungshin Women\'s University');
insert ignore into STATIONS (STATION_NAME) values ('Hansung University');
insert ignore into STATIONS (STATION_NAME) values ('Hyehwa');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun History and Culture Park');
insert ignore into STATIONS (STATION_NAME) values ('Chungmuro');
insert ignore into STATIONS (STATION_NAME) values ('Myeong-dong');
insert ignore into STATIONS (STATION_NAME) values ('Hoehyeon');
insert ignore into STATIONS (STATION_NAME) values ('Seoul');
insert ignore into STATIONS (STATION_NAME) values ('Sookmyung University');
insert ignore into STATIONS (STATION_NAME) values ('Triangle area');
insert ignore into STATIONS (STATION_NAME) values ('Shinyongsan');
insert ignore into STATIONS (STATION_NAME) values ('Ichon');
insert ignore into STATIONS (STATION_NAME) values ('Dongjak');
insert ignore into STATIONS (STATION_NAME) values ('Isu');
insert ignore into STATIONS (STATION_NAME) values ('Sadang');
insert ignore into STATIONS (STATION_NAME) values ('Namtaryeong');
insert ignore into STATIONS (STATION_NAME) values ('Sunbawi');
insert ignore into STATIONS (STATION_NAME) values ('Gyeongma Park');
insert ignore into STATIONS (STATION_NAME) values ('Grand Park');
insert ignore into STATIONS (STATION_NAME) values ('Gwacheon');
insert ignore into STATIONS (STATION_NAME) values ('Gwacheon Government Complex');
insert ignore into STATIONS (STATION_NAME) values ('Indeokwon');
insert ignore into STATIONS (STATION_NAME) values ('Pyeongchon');
insert ignore into STATIONS (STATION_NAME) values ('Beomgye');
insert ignore into STATIONS (STATION_NAME) values ('Geumjeong');
insert ignore into STATIONS (STATION_NAME) values ('Sanbon');
insert ignore into STATIONS (STATION_NAME) values ('Surisan');
insert ignore into STATIONS (STATION_NAME) values ('Daeyami');
insert ignore into STATIONS (STATION_NAME) values ('Banwol');
insert ignore into STATIONS (STATION_NAME) values ('Sangnoksu');
insert ignore into STATIONS (STATION_NAME) values ('Hankuk University');
insert ignore into STATIONS (STATION_NAME) values ('Central');
insert ignore into STATIONS (STATION_NAME) values ('Gojan');
insert ignore into STATIONS (STATION_NAME) values ('super-region');
insert ignore into STATIONS (STATION_NAME) values ('Ansan');
insert ignore into STATIONS (STATION_NAME) values ('Singil Oncheon');
insert ignore into STATIONS (STATION_NAME) values ('Jeongwang');
insert ignore into STATIONS (STATION_NAME) values ('Oido');
insert ignore into STATIONS (STATION_NAME) values ('Banghwa');
insert ignore into STATIONS (STATION_NAME) values ('Gaehwasan');
insert ignore into STATIONS (STATION_NAME) values ('Gimpo Airport');
insert ignore into STATIONS (STATION_NAME) values ('Songjeong');
insert ignore into STATIONS (STATION_NAME) values ('Magok');
insert ignore into STATIONS (STATION_NAME) values ('Balsan');
insert ignore into STATIONS (STATION_NAME) values ('Ujangsan');
insert ignore into STATIONS (STATION_NAME) values ('Hwagok');
insert ignore into STATIONS (STATION_NAME) values ('Kkachisan');
insert ignore into STATIONS (STATION_NAME) values ('Sinjeong');
insert ignore into STATIONS (STATION_NAME) values ('Mokdong');
insert ignore into STATIONS (STATION_NAME) values ('Omok Bridge');
insert ignore into STATIONS (STATION_NAME) values ('Yangpyeong');
insert ignore into STATIONS (STATION_NAME) values ('Yeongdeungpo-gu Office');
insert ignore into STATIONS (STATION_NAME) values ('Yeongdeungpo Market');
insert ignore into STATIONS (STATION_NAME) values ('Singil');
insert ignore into STATIONS (STATION_NAME) values ('Yeouido');
insert ignore into STATIONS (STATION_NAME) values ('Y ¿©ÀÇinaru');
insert ignore into STATIONS (STATION_NAME) values ('Mapo');
insert ignore into STATIONS (STATION_NAME) values ('Gongdeok');
insert ignore into STATIONS (STATION_NAME) values ('Aeogae');
insert ignore into STATIONS (STATION_NAME) values ('Chungjeongno');
insert ignore into STATIONS (STATION_NAME) values ('Seodaemun');
insert ignore into STATIONS (STATION_NAME) values ('Gwanghwamun');
insert ignore into STATIONS (STATION_NAME) values ('Jongno 3-ga');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro 4-ga');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun History and Culture Park');
insert ignore into STATIONS (STATION_NAME) values ('Cheonggu');
insert ignore into STATIONS (STATION_NAME) values ('Singeumho');
insert ignore into STATIONS (STATION_NAME) values ('Haengdang');
insert ignore into STATIONS (STATION_NAME) values ('Wangsimni');
insert ignore into STATIONS (STATION_NAME) values ('Majang');
insert ignore into STATIONS (STATION_NAME) values ('Dapsimni');
insert ignore into STATIONS (STATION_NAME) values ('Janghanpyeong');
insert ignore into STATIONS (STATION_NAME) values ('Gunja');
insert ignore into STATIONS (STATION_NAME) values ('Achasan');
insert ignore into STATIONS (STATION_NAME) values ('Gwangnaru');
insert ignore into STATIONS (STATION_NAME) values ('Cheonho');
insert ignore into STATIONS (STATION_NAME) values ('Gangdong');
insert ignore into STATIONS (STATION_NAME) values ('Gildong');
insert ignore into STATIONS (STATION_NAME) values ('Bendari');
insert ignore into STATIONS (STATION_NAME) values ('Myeongil');
insert ignore into STATIONS (STATION_NAME) values ('Godeok');
insert ignore into STATIONS (STATION_NAME) values ('Sangil-dong');
insert ignore into STATIONS (STATION_NAME) values ('Dunchon-dong');
insert ignore into STATIONS (STATION_NAME) values ('Olympic Park');
insert ignore into STATIONS (STATION_NAME) values ('Bangi');
insert ignore into STATIONS (STATION_NAME) values ('Ogeum');
insert ignore into STATIONS (STATION_NAME) values ('Gaerong');
insert ignore into STATIONS (STATION_NAME) values ('Geoyeo');
insert ignore into STATIONS (STATION_NAME) values ('Macheon');
insert ignore into STATIONS (STATION_NAME) values ('Eungam');
insert ignore into STATIONS (STATION_NAME) values ('Yeokchon');
insert ignore into STATIONS (STATION_NAME) values ('Bulgwang');
insert ignore into STATIONS (STATION_NAME) values ('Dokbawi');
insert ignore into STATIONS (STATION_NAME) values ('Yeonsinnae');
insert ignore into STATIONS (STATION_NAME) values ('Gusan');
insert ignore into STATIONS (STATION_NAME) values ('Saejeol');
insert ignore into STATIONS (STATION_NAME) values ('Jeungsan');
insert ignore into STATIONS (STATION_NAME) values ('Digital Media City');
insert ignore into STATIONS (STATION_NAME) values ('World Cup Stadium');
insert ignore into STATIONS (STATION_NAME) values ('Mapo-gu Office');
insert ignore into STATIONS (STATION_NAME) values ('Mangwon');
insert ignore into STATIONS (STATION_NAME) values ('Hapjeong');
insert ignore into STATIONS (STATION_NAME) values ('Sangsu');
insert ignore into STATIONS (STATION_NAME) values ('Gwangheungchang');
insert ignore into STATIONS (STATION_NAME) values ('Daeheung');
insert ignore into STATIONS (STATION_NAME) values ('Gongdeok');
insert ignore into STATIONS (STATION_NAME) values ('Hyochang Park');
insert ignore into STATIONS (STATION_NAME) values ('Triangle area');
insert ignore into STATIONS (STATION_NAME) values ('Noksapyeong');
insert ignore into STATIONS (STATION_NAME) values ('Itaewon');
insert ignore into STATIONS (STATION_NAME) values ('Hangangjin');
insert ignore into STATIONS (STATION_NAME) values ('Bertigogae');
insert ignore into STATIONS (STATION_NAME) values ('Yaksu');
insert ignore into STATIONS (STATION_NAME) values ('Cheonggu');
insert ignore into STATIONS (STATION_NAME) values ('Sindang');
insert ignore into STATIONS (STATION_NAME) values ('Dongmyo');
insert ignore into STATIONS (STATION_NAME) values ('Changshin');
insert ignore into STATIONS (STATION_NAME) values ('Bomun');
insert ignore into STATIONS (STATION_NAME) values ('Anam');
insert ignore into STATIONS (STATION_NAME) values ('Korea University');
insert ignore into STATIONS (STATION_NAME) values ('Wolgok');
insert ignore into STATIONS (STATION_NAME) values ('Sangwolgok');
insert ignore into STATIONS (STATION_NAME) values ('Dolgotji');
insert ignore into STATIONS (STATION_NAME) values ('Seokgye');
insert ignore into STATIONS (STATION_NAME) values ('Taereung');
insert ignore into STATIONS (STATION_NAME) values ('Hwarangdae');
insert ignore into STATIONS (STATION_NAME) values ('Bonghwasan');
insert ignore into STATIONS (STATION_NAME) values ('Jangam');
insert ignore into STATIONS (STATION_NAME) values ('Dobongsan');
insert ignore into STATIONS (STATION_NAME) values ('Suraksan');
insert ignore into STATIONS (STATION_NAME) values ('Madele');
insert ignore into STATIONS (STATION_NAME) values ('Nowon');
insert ignore into STATIONS (STATION_NAME) values ('relay');
insert ignore into STATIONS (STATION_NAME) values ('Summer');
insert ignore into STATIONS (STATION_NAME) values ('Gongneung');
insert ignore into STATIONS (STATION_NAME) values ('Taereung');
insert ignore into STATIONS (STATION_NAME) values ('Mukgol');
insert ignore into STATIONS (STATION_NAME) values ('Junghwa');
insert ignore into STATIONS (STATION_NAME) values ('Sangbong');
insert ignore into STATIONS (STATION_NAME) values ('Myeonmok');
insert ignore into STATIONS (STATION_NAME) values ('Sagam');
insert ignore into STATIONS (STATION_NAME) values ('Yongmasan');
insert ignore into STATIONS (STATION_NAME) values ('Junggok');
insert ignore into STATIONS (STATION_NAME) values ('Gunja');
insert ignore into STATIONS (STATION_NAME) values ('Children\'s Grand Park');
insert ignore into STATIONS (STATION_NAME) values ('Konkuk University');
insert ignore into STATIONS (STATION_NAME) values ('Ttuk Textile Garden Area');
insert ignore into STATIONS (STATION_NAME) values ('Cheongdam');
insert ignore into STATIONS (STATION_NAME) values ('Gangnam-gu Office');
insert ignore into STATIONS (STATION_NAME) values ('Hakdong');
insert ignore into STATIONS (STATION_NAME) values ('Nonhyeon');
insert ignore into STATIONS (STATION_NAME) values ('Banpo');
insert ignore into STATIONS (STATION_NAME) values ('Express Bus Terminal');
insert ignore into STATIONS (STATION_NAME) values ('Naebang');
insert ignore into STATIONS (STATION_NAME) values ('Isu');
insert ignore into STATIONS (STATION_NAME) values ('Namseong');
insert ignore into STATIONS (STATION_NAME) values ('Soongsil University');
insert ignore into STATIONS (STATION_NAME) values ('Sangdo');
insert ignore into STATIONS (STATION_NAME) values ('Jangseungbaegi');
insert ignore into STATIONS (STATION_NAME) values ('Sindaebang Samgeori');
insert ignore into STATIONS (STATION_NAME) values ('Boramae');
insert ignore into STATIONS (STATION_NAME) values ('Sinpung');
insert ignore into STATIONS (STATION_NAME) values ('Daelim');
insert ignore into STATIONS (STATION_NAME) values ('Namguro');
insert ignore into STATIONS (STATION_NAME) values ('Gasan Digital Complex Area');
insert ignore into STATIONS (STATION_NAME) values ('Cheolsan');
insert ignore into STATIONS (STATION_NAME) values ('Gwangmyeong Intersection');
insert ignore into STATIONS (STATION_NAME) values ('Cheonwang');
insert ignore into STATIONS (STATION_NAME) values ('Onsu');
insert ignore into STATIONS (STATION_NAME) values ('Kkachiul');
insert ignore into STATIONS (STATION_NAME) values ('Bucheon Stadium');
insert ignore into STATIONS (STATION_NAME) values ('Chunui');
insert ignore into STATIONS (STATION_NAME) values ('Sinjung-dong');
insert ignore into STATIONS (STATION_NAME) values ('Bucheon City Hall');
insert ignore into STATIONS (STATION_NAME) values ('Sangdong');
insert ignore into STATIONS (STATION_NAME) values ('Samsan Gymnasium');
insert ignore into STATIONS (STATION_NAME) values ('Gulpocheon');
insert ignore into STATIONS (STATION_NAME) values ('Bupyeong-gu Office');
insert ignore into STATIONS (STATION_NAME) values ('Amsa');
insert ignore into STATIONS (STATION_NAME) values ('Cheonho');
insert ignore into STATIONS (STATION_NAME) values ('Gangdong-gu Office');
insert ignore into STATIONS (STATION_NAME) values ('Mongchontoseong');
insert ignore into STATIONS (STATION_NAME) values ('Jamsil');
insert ignore into STATIONS (STATION_NAME) values ('Seokchon');
insert ignore into STATIONS (STATION_NAME) values ('Songpa');
insert ignore into STATIONS (STATION_NAME) values ('Garak Market');
insert ignore into STATIONS (STATION_NAME) values ('Munjeong');
insert ignore into STATIONS (STATION_NAME) values ('Zhang Ziyi');
insert ignore into STATIONS (STATION_NAME) values ('Bokjeong');
insert ignore into STATIONS (STATION_NAME) values ('Sanseong');
insert ignore into STATIONS (STATION_NAME) values ('Namhansanseong');
insert ignore into STATIONS (STATION_NAME) values ('Dandae Ogeori');
insert ignore into STATIONS (STATION_NAME) values ('Shinheung');
insert ignore into STATIONS (STATION_NAME) values ('Sujin');
insert ignore into STATIONS (STATION_NAME) values ('Moran');
insert ignore into STATIONS (STATION_NAME) values ('Gaehwa');
insert ignore into STATIONS (STATION_NAME) values ('Gimpo Airport');
insert ignore into STATIONS (STATION_NAME) values ('Airport Market');
insert ignore into STATIONS (STATION_NAME) values ('Sinbanghwa');
insert ignore into STATIONS (STATION_NAME) values ('Magoknaru');
insert ignore into STATIONS (STATION_NAME) values ('Yangcheonhyanggyo');
insert ignore into STATIONS (STATION_NAME) values ('Gayang');
insert ignore into STATIONS (STATION_NAME) values ('Jeungmi');
insert ignore into STATIONS (STATION_NAME) values ('Deungchon');
insert ignore into STATIONS (STATION_NAME) values ('Yeomchang');
insert ignore into STATIONS (STATION_NAME) values ('Sinmok-dong');
insert ignore into STATIONS (STATION_NAME) values ('Seonyudo');
insert ignore into STATIONS (STATION_NAME) values ('Dangsan');
insert ignore into STATIONS (STATION_NAME) values ('National Assembly Building');
insert ignore into STATIONS (STATION_NAME) values ('Yeouido');
insert ignore into STATIONS (STATION_NAME) values ('Saetgang');
insert ignore into STATIONS (STATION_NAME) values ('Noryangjin');
insert ignore into STATIONS (STATION_NAME) values ('Nodeul');
insert ignore into STATIONS (STATION_NAME) values ('Heukseok');
insert ignore into STATIONS (STATION_NAME) values ('Dongjak');
insert ignore into STATIONS (STATION_NAME) values ('Gubanpo');
insert ignore into STATIONS (STATION_NAME) values ('Sinbanpo');
insert ignore into STATIONS (STATION_NAME) values ('Express Bus Terminal');
insert ignore into STATIONS (STATION_NAME) values ('Sapyeong');
insert ignore into STATIONS (STATION_NAME) values ('Sinnonhyeon');
insert ignore into STATIONS (STATION_NAME) values ('Eonju');
insert ignore into STATIONS (STATION_NAME) values ('Seonjeongneung');
insert ignore into STATIONS (STATION_NAME) values ('Samseong Central');
insert ignore into STATIONS (STATION_NAME) values ('Bongeunsa');
insert ignore into STATIONS (STATION_NAME) values ('Sports Complex');
insert ignore into STATIONS (STATION_NAME) values ('Samjeon');
insert ignore into STATIONS (STATION_NAME) values ('Seokchon Ancient Tombs');
insert ignore into STATIONS (STATION_NAME) values ('Seokchon');
insert ignore into STATIONS (STATION_NAME) values ('Songpa Naru');
insert ignore into STATIONS (STATION_NAME) values ('Hansung Baekje');
insert ignore into STATIONS (STATION_NAME) values ('Olympic Park');
insert ignore into STATIONS (STATION_NAME) values ('Dunchon Oryun');
insert ignore into STATIONS (STATION_NAME) values ('Central Veterans Hospital');
