insert into STATIONS (STATION_NAME, RATE) values ('Dongducheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bosan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongducheon Central', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jihaeng', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Deokjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Deokgye', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yangju', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nokyang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('possible', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Uijeongbu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hoeryong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mangwolsa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dobongsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dobong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Banghak', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Changdong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nokcheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Wolgye', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Kwangwoon University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seokgye', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinimun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hankuk University of Foreign Studies', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hoegi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheongnyangni', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jegi-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinseol-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongmyo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongdaemun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jongno 5-ga', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jongno 3-ga', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jonggak', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('City Hall', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seoul', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Namyeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yongsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Noryangjin', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daebang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Singil', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeongdeungpo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sindorim', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Guro', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Guil', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('opening', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Oryu-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Onsu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeokgok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sosa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bucheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jungdong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Songnae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bugae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bupyeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Baegun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongam', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ganseok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Juan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dohwa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jemulpo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dowon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('East Incheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Incheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gasan Digital Complex Area', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Doksan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Geumcheon-gu Office', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gwangmyeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seoksu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gwanak', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Anyang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Myeonghak', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Geumjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gunpo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dangjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Uiwang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sungkyunkwan University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hwaseo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Suwon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seryu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Byeongjeom', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seodongtan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sema', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Osan University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Osan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jinwi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Songtan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seojeongri', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jije', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Pyeongtaek', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seonghwan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jiksan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dujeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheonan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bongmyeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ssangyong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Asan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Baebang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Onyang Hot Spring', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinchang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('City Hall', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Euljiro', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Euljiro 3-ga', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Euljiro 4-ga', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongdaemun History and Culture Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sindang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sangwangsimni', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Wangsimni', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hanyang University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ttukseom', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seongsu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yongdap', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sindap', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yongdu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinseol-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Konkuk University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Guui', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gangbyeon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jamsilnaru', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jamsil', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jamsil Saenae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sports Complex', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Samseong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seonreung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeoksam', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gangnam', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('abutment', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seocho', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bangbae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sadang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nakseongdae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seoul National University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bongcheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sillim', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sindaebang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Guro Digital Complex Area', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daelim', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sindorim', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dorimcheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yangcheon-gu Office', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinjeongnegeori', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Kkachisan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Munrae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeongdeungpo-gu Office', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dangsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hapjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hongdae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinchon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ewha Womans University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ahyeon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Chungjeongno', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Wonheung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daehwa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Juyeop', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jeongbalsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Madu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Baekseok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daegok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hwajeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Wondang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Samsong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jichuk', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gupabal', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeonsinnae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bulgwang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nokbeon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hongje', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Muakjae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Independence Literature Translation', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gyeongbokgung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Anguk', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jongno 3-ga', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Euljiro 3-ga', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Chungmuro', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongdaegu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yaksu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Kumho', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Oksu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Apgujeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinsa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jamwon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Express Bus Terminal', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('abutment', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nambu Terminal', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yangjae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Maebong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dogok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daechi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hakyeoul', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daecheong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ilwon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Suseo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Garak Market', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Police Hospital', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ogeum', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dangogae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sanggye', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nowon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Changdong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ssangmun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Suyu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mia', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mia Intersection', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gileum', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sungshin Women\'s University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hansung University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hyehwa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongdaemun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongdaemun History and Culture Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Chungmuro', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Myeong-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hoehyeon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seoul', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sookmyung University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Triangle area', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Shinyongsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ichon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongjak', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Isu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sadang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Namtaryeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sunbawi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gyeongma Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Grand Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gwacheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gwacheon Government Complex', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Indeokwon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Pyeongchon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Beomgye', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Geumjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sanbon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Surisan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daeyami', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Banwol', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sangnoksu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hankuk University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Central', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gojan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('super-region', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ansan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Singil Oncheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jeongwang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Oido', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Banghwa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gaehwasan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gimpo Airport', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Songjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Magok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Balsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ujangsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hwagok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Kkachisan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mokdong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Omok Bridge', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yangpyeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeongdeungpo-gu Office', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeongdeungpo Market', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Singil', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeouido', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Y ¿©ÀÇinaru', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mapo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gongdeok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Aeogae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Chungjeongno', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seodaemun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gwanghwamun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jongno 3-ga', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Euljiro 4-ga', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongdaemun History and Culture Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheonggu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Singeumho', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Haengdang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Wangsimni', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Majang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dapsimni', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Janghanpyeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gunja', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Achasan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gwangnaru', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheonho', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gangdong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gildong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bendari', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Myeongil', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Godeok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sangil-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dunchon-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Olympic Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bangi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ogeum', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gaerong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Geoyeo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Macheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Eungam', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeokchon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bulgwang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dokbawi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeonsinnae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gusan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Saejeol', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jeungsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Digital Media City', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('World Cup Stadium', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mapo-gu Office', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mangwon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hapjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sangsu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gwangheungchang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daeheung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gongdeok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hyochang Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Triangle area', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Noksapyeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Itaewon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hangangjin', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bertigogae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yaksu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheonggu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sindang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongmyo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Changshin', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bomun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Anam', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Korea University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Wolgok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sangwolgok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dolgotji', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seokgye', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Taereung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hwarangdae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bonghwasan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jangam', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dobongsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Suraksan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Madele', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nowon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('relay', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Summer', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gongneung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Taereung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mukgol', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Junghwa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sangbong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Myeonmok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sagam', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yongmasan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Junggok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gunja', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Children\'s Grand Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Konkuk University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Ttuk Textile Garden Area', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheongdam', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gangnam-gu Office', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hakdong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nonhyeon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Banpo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Express Bus Terminal', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Naebang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Isu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Namseong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Soongsil University', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sangdo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jangseungbaegi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sindaebang Samgeori', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Boramae', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinpung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Daelim', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Namguro', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gasan Digital Complex Area', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheolsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gwangmyeong Intersection', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheonwang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Onsu', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Kkachiul', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bucheon Stadium', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Chunui', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinjung-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bucheon City Hall', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sangdong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Samsan Gymnasium', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gulpocheon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bupyeong-gu Office', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Amsa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Cheonho', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gangdong-gu Office', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Mongchontoseong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jamsil', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seokchon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Songpa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Garak Market', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Munjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Zhang Ziyi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bokjeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sanseong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Namhansanseong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dandae Ogeori', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Shinheung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sujin', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Moran', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gaehwa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gimpo Airport', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Airport Market', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinbanghwa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Magoknaru', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yangcheonhyanggyo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gayang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Jeungmi', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Deungchon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeomchang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinmok-dong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seonyudo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dangsan', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('National Assembly Building', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Yeouido', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Saetgang', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Noryangjin', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Nodeul', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Heukseok', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dongjak', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Gubanpo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinbanpo', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Express Bus Terminal', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sapyeong', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sinnonhyeon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Eonju', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seonjeongneung', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Samseong Central', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Bongeunsa', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Sports Complex', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Samjeon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seokchon Ancient Tombs', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Seokchon', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Songpa Naru', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Hansung Baekje', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Olympic Park', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Dunchon Oryun', '1.000000');
insert into STATIONS (STATION_NAME, RATE) values ('Central Veterans Hospital', '1.000000');
