insert ignore into STATIONS (STATION_NAME) values ('Soyosan Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongducheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Bosan Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongducheon Central Station');
insert ignore into STATIONS (STATION_NAME) values ('Jihaeng Station');
insert ignore into STATIONS (STATION_NAME) values ('Deokjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Deokgye Station');
insert ignore into STATIONS (STATION_NAME) values ('Yangju Station');
insert ignore into STATIONS (STATION_NAME) values ('Nokyang Station');
insert ignore into STATIONS (STATION_NAME) values ('possible station');
insert ignore into STATIONS (STATION_NAME) values ('Uijeongbu Station');
insert ignore into STATIONS (STATION_NAME) values ('Hoeryong Station');
insert ignore into STATIONS (STATION_NAME) values ('Mangwolsa Station');
insert ignore into STATIONS (STATION_NAME) values ('Dobongsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Dobong Station');
insert ignore into STATIONS (STATION_NAME) values ('Banghak Station');
insert ignore into STATIONS (STATION_NAME) values ('Changdong Station');
insert ignore into STATIONS (STATION_NAME) values ('Nokcheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Wolgye Station');
insert ignore into STATIONS (STATION_NAME) values ('Kwangwoon University Station');
insert ignore into STATIONS (STATION_NAME) values ('Seokgye Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinimun Station');
insert ignore into STATIONS (STATION_NAME) values ('Hankuk University of Foreign Studies station');
insert ignore into STATIONS (STATION_NAME) values ('Hoegi Station');
insert ignore into STATIONS (STATION_NAME) values ('Cheongnyangni Station');
insert ignore into STATIONS (STATION_NAME) values ('Jegi-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinseol-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongmyo Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun Station');
insert ignore into STATIONS (STATION_NAME) values ('Jongno 5-ga Station');
insert ignore into STATIONS (STATION_NAME) values ('Jongno 3-ga Station');
insert ignore into STATIONS (STATION_NAME) values ('Jonggak Station');
insert ignore into STATIONS (STATION_NAME) values ('City Hall Station');
insert ignore into STATIONS (STATION_NAME) values ('Seoul Station');
insert ignore into STATIONS (STATION_NAME) values ('Namyeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Yongsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Noryangjin Station');
insert ignore into STATIONS (STATION_NAME) values ('Daebang Station');
insert ignore into STATIONS (STATION_NAME) values ('Singil Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeongdeungpo Station');
insert ignore into STATIONS (STATION_NAME) values ('Sindorim Station');
insert ignore into STATIONS (STATION_NAME) values ('Guro Station');
insert ignore into STATIONS (STATION_NAME) values ('Guil Station');
insert ignore into STATIONS (STATION_NAME) values ('opening station');
insert ignore into STATIONS (STATION_NAME) values ('Oryu-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Onsu Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeokgok Station');
insert ignore into STATIONS (STATION_NAME) values ('Sosa Station');
insert ignore into STATIONS (STATION_NAME) values ('Bucheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Jungdong Station');
insert ignore into STATIONS (STATION_NAME) values ('Songnae Station');
insert ignore into STATIONS (STATION_NAME) values ('Bugae Station');
insert ignore into STATIONS (STATION_NAME) values ('Bupyeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Baegun Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongam Station');
insert ignore into STATIONS (STATION_NAME) values ('Ganseok Station');
insert ignore into STATIONS (STATION_NAME) values ('Juan Station');
insert ignore into STATIONS (STATION_NAME) values ('Dohwa Station');
insert ignore into STATIONS (STATION_NAME) values ('Jemulpo Station');
insert ignore into STATIONS (STATION_NAME) values ('Dowon Station');
insert ignore into STATIONS (STATION_NAME) values ('East Incheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Incheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Gasan Digital Complex Area');
insert ignore into STATIONS (STATION_NAME) values ('Doksan Station');
insert ignore into STATIONS (STATION_NAME) values ('Geumcheon-gu Office Station');
insert ignore into STATIONS (STATION_NAME) values ('Gwangmyeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Seoksu Station');
insert ignore into STATIONS (STATION_NAME) values ('Gwanak Station');
insert ignore into STATIONS (STATION_NAME) values ('Anyang Station');
insert ignore into STATIONS (STATION_NAME) values ('Myeonghak Station');
insert ignore into STATIONS (STATION_NAME) values ('Geumjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Gunpo Station');
insert ignore into STATIONS (STATION_NAME) values ('Dangjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Uiwang Station');
insert ignore into STATIONS (STATION_NAME) values ('Sungkyunkwan University Station');
insert ignore into STATIONS (STATION_NAME) values ('Hwaseo Station');
insert ignore into STATIONS (STATION_NAME) values ('Suwon Station');
insert ignore into STATIONS (STATION_NAME) values ('Seryu Station');
insert ignore into STATIONS (STATION_NAME) values ('Byeongjeom Station');
insert ignore into STATIONS (STATION_NAME) values ('Seodongtan Station');
insert ignore into STATIONS (STATION_NAME) values ('Sema Station');
insert ignore into STATIONS (STATION_NAME) values ('Osan University Station');
insert ignore into STATIONS (STATION_NAME) values ('Osan Station');
insert ignore into STATIONS (STATION_NAME) values ('Jinwi Station');
insert ignore into STATIONS (STATION_NAME) values ('Songtan Station');
insert ignore into STATIONS (STATION_NAME) values ('Seojeongri Station');
insert ignore into STATIONS (STATION_NAME) values ('Jije Station');
insert ignore into STATIONS (STATION_NAME) values ('Pyeongtaek Station');
insert ignore into STATIONS (STATION_NAME) values ('Seonghwan Station');
insert ignore into STATIONS (STATION_NAME) values ('Jiksan Station');
insert ignore into STATIONS (STATION_NAME) values ('Dujeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Cheonan Station');
insert ignore into STATIONS (STATION_NAME) values ('Bongmyeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Ssangyong Station');
insert ignore into STATIONS (STATION_NAME) values ('Asan Station');
insert ignore into STATIONS (STATION_NAME) values ('Baebang Station');
insert ignore into STATIONS (STATION_NAME) values ('Onyang Hot Spring Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinchang Station');
insert ignore into STATIONS (STATION_NAME) values ('City Hall Station');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro Station');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro 3-ga Station');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro 4-ga Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun History and Culture Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Sindang Station');
insert ignore into STATIONS (STATION_NAME) values ('Sangwangsimni Station');
insert ignore into STATIONS (STATION_NAME) values ('Wangsimni Station');
insert ignore into STATIONS (STATION_NAME) values ('Hanyang University Station');
insert ignore into STATIONS (STATION_NAME) values ('Ttukseom Station');
insert ignore into STATIONS (STATION_NAME) values ('Seongsu Station');
insert ignore into STATIONS (STATION_NAME) values ('Yongdap Station');
insert ignore into STATIONS (STATION_NAME) values ('Sindap Station');
insert ignore into STATIONS (STATION_NAME) values ('Yongdu Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinseol-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Konkuk University Station');
insert ignore into STATIONS (STATION_NAME) values ('Guui Station');
insert ignore into STATIONS (STATION_NAME) values ('Gangbyeon Station');
insert ignore into STATIONS (STATION_NAME) values ('Jamsilnaru Station');
insert ignore into STATIONS (STATION_NAME) values ('Jamsil Station');
insert ignore into STATIONS (STATION_NAME) values ('Jamsil Saenae Station');
insert ignore into STATIONS (STATION_NAME) values ('Sports Complex Station');
insert ignore into STATIONS (STATION_NAME) values ('Samseong Station');
insert ignore into STATIONS (STATION_NAME) values ('Seonreung Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeoksam Station');
insert ignore into STATIONS (STATION_NAME) values ('Gangnam Station');
insert ignore into STATIONS (STATION_NAME) values ('abutment station');
insert ignore into STATIONS (STATION_NAME) values ('Seocho Station');
insert ignore into STATIONS (STATION_NAME) values ('Bangbae Station');
insert ignore into STATIONS (STATION_NAME) values ('Sadang Station');
insert ignore into STATIONS (STATION_NAME) values ('Nakseongdae Station');
insert ignore into STATIONS (STATION_NAME) values ('Seoul National University Station');
insert ignore into STATIONS (STATION_NAME) values ('Bongcheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Sillim Station');
insert ignore into STATIONS (STATION_NAME) values ('Sindaebang Station');
insert ignore into STATIONS (STATION_NAME) values ('Guro Digital Complex Area');
insert ignore into STATIONS (STATION_NAME) values ('Daelim Station');
insert ignore into STATIONS (STATION_NAME) values ('Sindorim Station');
insert ignore into STATIONS (STATION_NAME) values ('Dorimcheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Yangcheon-gu Office Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinjeongnegeori Station');
insert ignore into STATIONS (STATION_NAME) values ('Kkachisan Station');
insert ignore into STATIONS (STATION_NAME) values ('Munrae Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeongdeungpo-gu Office Station');
insert ignore into STATIONS (STATION_NAME) values ('Dangsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Hapjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Hongdae Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinchon Station');
insert ignore into STATIONS (STATION_NAME) values ('Ewha Womans University Station');
insert ignore into STATIONS (STATION_NAME) values ('Ahyeon Station');
insert ignore into STATIONS (STATION_NAME) values ('Chungjeongno Station');
insert ignore into STATIONS (STATION_NAME) values ('Wonheung Station');
insert ignore into STATIONS (STATION_NAME) values ('Daehwa Station');
insert ignore into STATIONS (STATION_NAME) values ('Juyeop Station');
insert ignore into STATIONS (STATION_NAME) values ('Jeongbalsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Madu Station');
insert ignore into STATIONS (STATION_NAME) values ('Baekseok Station');
insert ignore into STATIONS (STATION_NAME) values ('Daegok Station');
insert ignore into STATIONS (STATION_NAME) values ('Hwajeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Wondang Station');
insert ignore into STATIONS (STATION_NAME) values ('Samsong Station');
insert ignore into STATIONS (STATION_NAME) values ('Jichuk Station');
insert ignore into STATIONS (STATION_NAME) values ('Gupabal Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeonsinnae Station');
insert ignore into STATIONS (STATION_NAME) values ('Bulgwang Station');
insert ignore into STATIONS (STATION_NAME) values ('Nokbeon Station');
insert ignore into STATIONS (STATION_NAME) values ('Hongje Station');
insert ignore into STATIONS (STATION_NAME) values ('Muakjae Station');
insert ignore into STATIONS (STATION_NAME) values ('Independence Literature Translation');
insert ignore into STATIONS (STATION_NAME) values ('Gyeongbokgung Station');
insert ignore into STATIONS (STATION_NAME) values ('Anguk Station');
insert ignore into STATIONS (STATION_NAME) values ('Jongno 3-ga Station');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro 3-ga Station');
insert ignore into STATIONS (STATION_NAME) values ('Chungmuro Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaegu Station');
insert ignore into STATIONS (STATION_NAME) values ('Yaksu Station');
insert ignore into STATIONS (STATION_NAME) values ('Kumho Station');
insert ignore into STATIONS (STATION_NAME) values ('Oksu Station');
insert ignore into STATIONS (STATION_NAME) values ('Apgujeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinsa Station');
insert ignore into STATIONS (STATION_NAME) values ('Jamwon Station');
insert ignore into STATIONS (STATION_NAME) values ('Express Bus Terminal Station');
insert ignore into STATIONS (STATION_NAME) values ('abutment station');
insert ignore into STATIONS (STATION_NAME) values ('Nambu Terminal Station');
insert ignore into STATIONS (STATION_NAME) values ('Yangjae Station');
insert ignore into STATIONS (STATION_NAME) values ('Maebong Station');
insert ignore into STATIONS (STATION_NAME) values ('Dogok Station');
insert ignore into STATIONS (STATION_NAME) values ('Daechi Station');
insert ignore into STATIONS (STATION_NAME) values ('Hakyeoul Station');
insert ignore into STATIONS (STATION_NAME) values ('Daecheong Station');
insert ignore into STATIONS (STATION_NAME) values ('Ilwon Station');
insert ignore into STATIONS (STATION_NAME) values ('Suseo Station');
insert ignore into STATIONS (STATION_NAME) values ('Garak Market Station');
insert ignore into STATIONS (STATION_NAME) values ('Police Hospital Station');
insert ignore into STATIONS (STATION_NAME) values ('Ogeum Station');
insert ignore into STATIONS (STATION_NAME) values ('Dangogae Station');
insert ignore into STATIONS (STATION_NAME) values ('Sanggye Station');
insert ignore into STATIONS (STATION_NAME) values ('Nowon Station');
insert ignore into STATIONS (STATION_NAME) values ('Changdong Station');
insert ignore into STATIONS (STATION_NAME) values ('Ssangmun Station');
insert ignore into STATIONS (STATION_NAME) values ('Suyu Station');
insert ignore into STATIONS (STATION_NAME) values ('Mia Station');
insert ignore into STATIONS (STATION_NAME) values ('Mia Intersection Station');
insert ignore into STATIONS (STATION_NAME) values ('Gileum Station');
insert ignore into STATIONS (STATION_NAME) values ('Sungshin Women\'s University Station');
insert ignore into STATIONS (STATION_NAME) values ('Hansung University Station');
insert ignore into STATIONS (STATION_NAME) values ('Hyehwa Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun History and Culture Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Chungmuro Station');
insert ignore into STATIONS (STATION_NAME) values ('Myeong-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Hoehyeon Station');
insert ignore into STATIONS (STATION_NAME) values ('Seoul Station');
insert ignore into STATIONS (STATION_NAME) values ('Sookmyung University Station');
insert ignore into STATIONS (STATION_NAME) values ('Triangle area');
insert ignore into STATIONS (STATION_NAME) values ('Shinyongsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Ichon Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongjak Station');
insert ignore into STATIONS (STATION_NAME) values ('Isu Station');
insert ignore into STATIONS (STATION_NAME) values ('Sadang Station');
insert ignore into STATIONS (STATION_NAME) values ('Namtaryeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Sunbawi Station');
insert ignore into STATIONS (STATION_NAME) values ('Gyeongma Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Grand Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Gwacheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Gwacheon Government Complex Station');
insert ignore into STATIONS (STATION_NAME) values ('Indeokwon Station');
insert ignore into STATIONS (STATION_NAME) values ('Pyeongchon Station');
insert ignore into STATIONS (STATION_NAME) values ('Beomgye Station');
insert ignore into STATIONS (STATION_NAME) values ('Geumjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Sanbon Station');
insert ignore into STATIONS (STATION_NAME) values ('Surisan Station');
insert ignore into STATIONS (STATION_NAME) values ('Daeyami Station');
insert ignore into STATIONS (STATION_NAME) values ('Banwol Station');
insert ignore into STATIONS (STATION_NAME) values ('Sangnoksu Station');
insert ignore into STATIONS (STATION_NAME) values ('Hankuk University Station');
insert ignore into STATIONS (STATION_NAME) values ('Central Station');
insert ignore into STATIONS (STATION_NAME) values ('Gojan Station');
insert ignore into STATIONS (STATION_NAME) values ('super-region');
insert ignore into STATIONS (STATION_NAME) values ('Ansan Station');
insert ignore into STATIONS (STATION_NAME) values ('Singil Oncheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Jeongwang Station');
insert ignore into STATIONS (STATION_NAME) values ('Oido Station');
insert ignore into STATIONS (STATION_NAME) values ('Banghwa Station');
insert ignore into STATIONS (STATION_NAME) values ('Gaehwasan Station');
insert ignore into STATIONS (STATION_NAME) values ('Gimpo Airport Station');
insert ignore into STATIONS (STATION_NAME) values ('Songjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Magok Station');
insert ignore into STATIONS (STATION_NAME) values ('Balsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Ujangsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Hwagok Station');
insert ignore into STATIONS (STATION_NAME) values ('Kkachisan Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Mokdong Station');
insert ignore into STATIONS (STATION_NAME) values ('Omok Bridge Station');
insert ignore into STATIONS (STATION_NAME) values ('Yangpyeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeongdeungpo-gu Office Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeongdeungpo Market Station');
insert ignore into STATIONS (STATION_NAME) values ('Singil Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeouido Station');
insert ignore into STATIONS (STATION_NAME) values ('Y ¿©ÀÇinaru Station');
insert ignore into STATIONS (STATION_NAME) values ('Mapo Station');
insert ignore into STATIONS (STATION_NAME) values ('Gongdeok Station');
insert ignore into STATIONS (STATION_NAME) values ('Aeogae Station');
insert ignore into STATIONS (STATION_NAME) values ('Chungjeongno Station');
insert ignore into STATIONS (STATION_NAME) values ('Seodaemun Station');
insert ignore into STATIONS (STATION_NAME) values ('Gwanghwamun Station');
insert ignore into STATIONS (STATION_NAME) values ('Jongno 3-ga Station');
insert ignore into STATIONS (STATION_NAME) values ('Euljiro 4-ga Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongdaemun History and Culture Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Cheonggu Station');
insert ignore into STATIONS (STATION_NAME) values ('Singeumho Station');
insert ignore into STATIONS (STATION_NAME) values ('Haengdang Station');
insert ignore into STATIONS (STATION_NAME) values ('Wangsimni Station');
insert ignore into STATIONS (STATION_NAME) values ('Majang Station');
insert ignore into STATIONS (STATION_NAME) values ('Dapsimni Station');
insert ignore into STATIONS (STATION_NAME) values ('Janghanpyeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Gunja Station');
insert ignore into STATIONS (STATION_NAME) values ('Achasan Station');
insert ignore into STATIONS (STATION_NAME) values ('Gwangnaru Station');
insert ignore into STATIONS (STATION_NAME) values ('Cheonho Station');
insert ignore into STATIONS (STATION_NAME) values ('Gangdong Station');
insert ignore into STATIONS (STATION_NAME) values ('Gildong Station');
insert ignore into STATIONS (STATION_NAME) values ('Bendari Station');
insert ignore into STATIONS (STATION_NAME) values ('Myeongil Station');
insert ignore into STATIONS (STATION_NAME) values ('Godeok Station');
insert ignore into STATIONS (STATION_NAME) values ('Sangil-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Dunchon-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Olympic Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Bangi Station');
insert ignore into STATIONS (STATION_NAME) values ('Ogeum Station');
insert ignore into STATIONS (STATION_NAME) values ('Gaerong Station');
insert ignore into STATIONS (STATION_NAME) values ('Geoyeo Station');
insert ignore into STATIONS (STATION_NAME) values ('Macheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Eungam Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeokchon Station');
insert ignore into STATIONS (STATION_NAME) values ('Bulgwang Station');
insert ignore into STATIONS (STATION_NAME) values ('Dokbawi Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeonsinnae Station');
insert ignore into STATIONS (STATION_NAME) values ('Gusan Station');
insert ignore into STATIONS (STATION_NAME) values ('Saejeol Station');
insert ignore into STATIONS (STATION_NAME) values ('Jeungsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Digital Media City Station');
insert ignore into STATIONS (STATION_NAME) values ('World Cup Stadium Station');
insert ignore into STATIONS (STATION_NAME) values ('Mapo-gu Office Station');
insert ignore into STATIONS (STATION_NAME) values ('Mangwon Station');
insert ignore into STATIONS (STATION_NAME) values ('Hapjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Sangsu Station');
insert ignore into STATIONS (STATION_NAME) values ('Gwangheungchang Station');
insert ignore into STATIONS (STATION_NAME) values ('Daeheung Station');
insert ignore into STATIONS (STATION_NAME) values ('Gongdeok Station');
insert ignore into STATIONS (STATION_NAME) values ('Hyochang Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Triangle area');
insert ignore into STATIONS (STATION_NAME) values ('Noksapyeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Itaewon Station');
insert ignore into STATIONS (STATION_NAME) values ('Hangangjin Station');
insert ignore into STATIONS (STATION_NAME) values ('Bertigogae Station');
insert ignore into STATIONS (STATION_NAME) values ('Yaksu Station');
insert ignore into STATIONS (STATION_NAME) values ('Cheonggu Station');
insert ignore into STATIONS (STATION_NAME) values ('Sindang Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongmyo Station');
insert ignore into STATIONS (STATION_NAME) values ('Changshin Station');
insert ignore into STATIONS (STATION_NAME) values ('Bomun Station');
insert ignore into STATIONS (STATION_NAME) values ('Anam Station');
insert ignore into STATIONS (STATION_NAME) values ('Korea University Station');
insert ignore into STATIONS (STATION_NAME) values ('Wolgok Station');
insert ignore into STATIONS (STATION_NAME) values ('Sangwolgok Station');
insert ignore into STATIONS (STATION_NAME) values ('Dolgotji Station');
insert ignore into STATIONS (STATION_NAME) values ('Seokgye Station');
insert ignore into STATIONS (STATION_NAME) values ('Taereung Station');
insert ignore into STATIONS (STATION_NAME) values ('Hwarangdae Station');
insert ignore into STATIONS (STATION_NAME) values ('Bonghwasan Station');
insert ignore into STATIONS (STATION_NAME) values ('Jangam Station');
insert ignore into STATIONS (STATION_NAME) values ('Dobongsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Suraksan Station');
insert ignore into STATIONS (STATION_NAME) values ('Madele Station');
insert ignore into STATIONS (STATION_NAME) values ('Nowon Station');
insert ignore into STATIONS (STATION_NAME) values ('relay station');
insert ignore into STATIONS (STATION_NAME) values ('Summer Station');
insert ignore into STATIONS (STATION_NAME) values ('Gongneung Station');
insert ignore into STATIONS (STATION_NAME) values ('Taereung Station');
insert ignore into STATIONS (STATION_NAME) values ('Mukgol Station');
insert ignore into STATIONS (STATION_NAME) values ('Junghwa Station');
insert ignore into STATIONS (STATION_NAME) values ('Sangbong Station');
insert ignore into STATIONS (STATION_NAME) values ('Myeonmok Station');
insert ignore into STATIONS (STATION_NAME) values ('Sagam Station');
insert ignore into STATIONS (STATION_NAME) values ('Yongmasan Station');
insert ignore into STATIONS (STATION_NAME) values ('Junggok Station');
insert ignore into STATIONS (STATION_NAME) values ('Gunja Station');
insert ignore into STATIONS (STATION_NAME) values ('Children\'s Grand Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Konkuk University Station');
insert ignore into STATIONS (STATION_NAME) values ('Ttuk Textile Garden Area');
insert ignore into STATIONS (STATION_NAME) values ('Cheongdam Station');
insert ignore into STATIONS (STATION_NAME) values ('Gangnam-gu Office Station');
insert ignore into STATIONS (STATION_NAME) values ('Hakdong Station');
insert ignore into STATIONS (STATION_NAME) values ('Nonhyeon Station');
insert ignore into STATIONS (STATION_NAME) values ('Banpo Station');
insert ignore into STATIONS (STATION_NAME) values ('Express Bus Terminal Station');
insert ignore into STATIONS (STATION_NAME) values ('Naebang Station');
insert ignore into STATIONS (STATION_NAME) values ('Isu Station');
insert ignore into STATIONS (STATION_NAME) values ('Namseong Station');
insert ignore into STATIONS (STATION_NAME) values ('Soongsil University Station');
insert ignore into STATIONS (STATION_NAME) values ('Sangdo Station');
insert ignore into STATIONS (STATION_NAME) values ('Jangseungbaegi Station');
insert ignore into STATIONS (STATION_NAME) values ('Sindaebang Samgeori Station');
insert ignore into STATIONS (STATION_NAME) values ('Boramae Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinpung Station');
insert ignore into STATIONS (STATION_NAME) values ('Daelim Station');
insert ignore into STATIONS (STATION_NAME) values ('Namguro Station');
insert ignore into STATIONS (STATION_NAME) values ('Gasan Digital Complex Area');
insert ignore into STATIONS (STATION_NAME) values ('Cheolsan Station');
insert ignore into STATIONS (STATION_NAME) values ('Gwangmyeong Intersection Station');
insert ignore into STATIONS (STATION_NAME) values ('Cheonwang Station');
insert ignore into STATIONS (STATION_NAME) values ('Onsu Station');
insert ignore into STATIONS (STATION_NAME) values ('Kkachiul Station');
insert ignore into STATIONS (STATION_NAME) values ('Bucheon Stadium Station');
insert ignore into STATIONS (STATION_NAME) values ('Chunui Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinjung-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Bucheon City Hall Station');
insert ignore into STATIONS (STATION_NAME) values ('Sangdong Station');
insert ignore into STATIONS (STATION_NAME) values ('Samsan Gymnasium Station');
insert ignore into STATIONS (STATION_NAME) values ('Gulpocheon Station');
insert ignore into STATIONS (STATION_NAME) values ('Bupyeong-gu Office Station');
insert ignore into STATIONS (STATION_NAME) values ('Amsa Station');
insert ignore into STATIONS (STATION_NAME) values ('Cheonho Station');
insert ignore into STATIONS (STATION_NAME) values ('Gangdong-gu Office Station');
insert ignore into STATIONS (STATION_NAME) values ('Mongchontoseong Station');
insert ignore into STATIONS (STATION_NAME) values ('Jamsil Station');
insert ignore into STATIONS (STATION_NAME) values ('Seokchon Station');
insert ignore into STATIONS (STATION_NAME) values ('Songpa Station');
insert ignore into STATIONS (STATION_NAME) values ('Garak Market Station');
insert ignore into STATIONS (STATION_NAME) values ('Munjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Zhang Ziyi');
insert ignore into STATIONS (STATION_NAME) values ('Bokjeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Sanseong Station');
insert ignore into STATIONS (STATION_NAME) values ('Namhansanseong Station');
insert ignore into STATIONS (STATION_NAME) values ('Dandae Ogeori Station');
insert ignore into STATIONS (STATION_NAME) values ('Shinheung Station');
insert ignore into STATIONS (STATION_NAME) values ('Sujin Station');
insert ignore into STATIONS (STATION_NAME) values ('Moran Station');
insert ignore into STATIONS (STATION_NAME) values ('Gaehwa Station');
insert ignore into STATIONS (STATION_NAME) values ('Gimpo Airport Station');
insert ignore into STATIONS (STATION_NAME) values ('Airport Market Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinbanghwa Station');
insert ignore into STATIONS (STATION_NAME) values ('Magoknaru Station');
insert ignore into STATIONS (STATION_NAME) values ('Yangcheonhyanggyo Station');
insert ignore into STATIONS (STATION_NAME) values ('Gayang Station');
insert ignore into STATIONS (STATION_NAME) values ('Jeungmi Station');
insert ignore into STATIONS (STATION_NAME) values ('Deungchon Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeomchang Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinmok-dong Station');
insert ignore into STATIONS (STATION_NAME) values ('Seonyudo Station');
insert ignore into STATIONS (STATION_NAME) values ('Dangsan Station');
insert ignore into STATIONS (STATION_NAME) values ('National Assembly Building Station');
insert ignore into STATIONS (STATION_NAME) values ('Yeouido Station');
insert ignore into STATIONS (STATION_NAME) values ('Saetgang Station');
insert ignore into STATIONS (STATION_NAME) values ('Noryangjin Station');
insert ignore into STATIONS (STATION_NAME) values ('Nodeul Station');
insert ignore into STATIONS (STATION_NAME) values ('Heukseok Station');
insert ignore into STATIONS (STATION_NAME) values ('Dongjak Station');
insert ignore into STATIONS (STATION_NAME) values ('Gubanpo Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinbanpo Station');
insert ignore into STATIONS (STATION_NAME) values ('Express Bus Terminal Station');
insert ignore into STATIONS (STATION_NAME) values ('Sapyeong Station');
insert ignore into STATIONS (STATION_NAME) values ('Sinnonhyeon Station');
insert ignore into STATIONS (STATION_NAME) values ('Eonju Station');
insert ignore into STATIONS (STATION_NAME) values ('Seonjeongneung Station');
insert ignore into STATIONS (STATION_NAME) values ('Samseong Central Station');
insert ignore into STATIONS (STATION_NAME) values ('Bongeunsa Station');
insert ignore into STATIONS (STATION_NAME) values ('Sports Complex Station');
insert ignore into STATIONS (STATION_NAME) values ('Samjeon Station');
insert ignore into STATIONS (STATION_NAME) values ('Seokchon Ancient Tombs Station');
insert ignore into STATIONS (STATION_NAME) values ('Seokchon Station');
insert ignore into STATIONS (STATION_NAME) values ('Songpa Naru Station');
insert ignore into STATIONS (STATION_NAME) values ('Hansung Baekje Station');
insert ignore into STATIONS (STATION_NAME) values ('Olympic Park Station');
insert ignore into STATIONS (STATION_NAME) values ('Dunchon Oryun Station');
insert ignore into STATIONS (STATION_NAME) values ('Central Veterans Hospital Station');
