update activities set ctgrgroup = '노래방' where ctgr = '노래방';
update activities set ctgrgroup = '테마카페' where ctgr = '보드카페';
update activities set ctgrgroup = 'PC방' where ctgr = 'PC방';
update activities set ctgrgroup = '테마카페' where ctgr = '룸카페';
update activities set ctgrgroup = '테마카페' where ctgr = '방탈출카페';
update activities set ctgrgroup = '구기종목, 야외' where ctgr = '당구장';
update activities set ctgrgroup = 'VR, 오락실' where ctgr = 'VR체험';
update activities set ctgrgroup = '구기종목, 야외' where ctgr = '스포츠시설';
update activities set ctgrgroup = 'VR, 오락실' where ctgr = '오락시설';
update activities set ctgrgroup = 'VR, 오락실' where ctgr = '오락실';
update activities set ctgrgroup = '구기종목, 야외' where ctgr = '롤러,인라인스케이트장';
update activities set ctgrgroup = '테마카페' where ctgr = '테마카페';
update activities set ctgrgroup = '테마카페' where ctgr = '이벤트,파티';
update activities set ctgrgroup = '구기종목, 야외' where ctgr = '볼링장';
update activities set ctgrgroup = '테마카페' where ctgr = '만화방';
update activities set ctgrgroup = '구기종목, 야외' where ctgr = '스크린야구장';
update activities set ctgrgroup = '구기종목, 야외' where ctgr = '낚시터';
update activities set ctgrgroup = '구기종목, 야외' where ctgr = '야구연습장';
update activities set ctgrgroup = 'VR, 오락실' where ctgr = '사격장';
update activities set ctgrgroup = '테마카페' where ctgr = '카페,디저트';
update activities set ctgrgroup = '테마카페' where ctgr = '공방';
update activities set ctgrgroup = '테마카페' where ctgr = '카페';
update activities set ctgrgroup = '테마카페' where ctgr = '전시관';
update activities set ctgrgroup = 'VR, 오락실' where ctgr = '양궁장';
update activities set ctgrgroup = '테마카페' where ctgr = '멀티방';
update activities set ctgrgroup = '테마카페' where ctgr = '북카페';
update activities set ctgrgroup = '테마카페' where ctgr = '사진,스튜디오';
